### ISSUE TITLE
README is wrong about IndentlessMap

### ISSUE THREAD

**Issue by perlpunk** [rurban/YAML-Safe#1]
The README says:
>    If you set the option $YAML::Safe::IndentlessMap to 0 or undef,
>    "YAML::Safe" will behave like with version < 0.70, which creates yml
>   files which cannot be read by "YAML.pm"

YAML.pm can do that since 1.26:
```
% echo "---
foo:
- a
- b
" | perl -wE'
use YAML;
use Data::Dumper;
say YAML->VERSION;
my $yaml = do { local $/ = <STDIN> };
my $data = Load($yaml);
say Dumper $data;'
1.29
$VAR1 = {
          'foo' => [
                     'a',
                     'b'
                   ]
        };

```
Further down:
```
    $YAML::Safe::IndentlessMap
        Default 0

        Set to 1 or a true value to fallback to the old "YAML::Safe"
        behavior to omit the indentation of map keys, which arguably
        violates the YAML spec, is different to all other YAML libraries and
        causes "YAML.pm" to fail.
```

It does not violate the spec, and "is different to all other YAML libraries" is wrong and I would like to see a proof.

https://yaml.org/spec/1.1/
> People read the “-” character as part of the indentation. Hence, block sequence entries require one less space of indentation, unless the block sequence is nested within another block sequence (hence the need for the block-in context and block-out context).

```
[197] seq-spaces(n,c) ::=	c = block-out ⇒ n-1
                                c = block-in  ⇒ n
```

**Comment by rurban** [comment]
This was from an very early README.

https://yaml.org/spec/1.0/
"The indentation level is always non-zero, except for the top level node of each document. This node is commonly indented by zero spaces (not indented)."

map keys are certainly not top level, hence indent 0 was explicitly forbidden. That's why most yaml writers do that. Ingy's later addition to the 1.1 spec violated the 1.0 spec, that's why nobody did that.

YAML.pm was for a long time not able to read it, hence it's forbidden to write such yaml for modules which fallback to YAML.pm, such as CPAN META.yml or distroprefs. CPAN got away by using it's secure and proprietary YAML 1.0 module in CPAN-META. 
1.2 tags made YAML insecure.
Hence the need for a safe YAML 1.2 module, with acceptable performance with a lot of external ~/.cpan/build/\*.yml and ~/.cpan/prefs/\*.yml files. The default is insecure and too slow.
YAML-Syck is fine, but some clueless people prefer the insecure yaml 1.2 version (similar to the damage done in the JSON spec updates), hence the need for a safe whitelisting version, such as in other languages.

**Comment by perlpunk** [comment]
> https://yaml.org/spec/1.0/

Oh right, you're taking a YAML 1.1 processor, and everyone should know that when you write "the spec", you mean the 1.0 one...

> "The indentation level is always non-zero, except for the top level node of each document. This node is commonly indented by zero spaces (not indented)."

My quote of the 1.0 spec actually says that sequences that are map values don't need to be indented:

> The “-” sequence entry, “?” complex key and “:” mapping entry indicators are perceived by people to be part of the indentation. Hence the indentation rules are slightly more flexible when dealing with these indicators. First, a block sequence need not be indented relative to its parent node, unless that node is a block sequence entry. For example:

> Example 4.1. 
```
a key in a mapping at indentation level 0:
# The value for this key is a block sequence.
- This sequence is also at indentation level 0.
-   Another entry in the sequence.
- # The value of this entry is a nested sequence.
 - This nested sequence must be
  indented at least to level 1.
 - Another entry in the nested sequence.
- Last entry in block sequence at indentation level 0.
second key in mapping: at indentation level 0.
```

But I admit that, other than that, I don't really know the 1.0 spec.

> map keys are certainly not top level, hence indent 0 was explicitly forbidden

I'm not sure what you mean. If you say map keys must always be indented more than 0, then the following would be invalid?
```
---
foo: bar
```

> That's why most yaml writers do that

What's your definition of "most"?

> Ingy's later addition to the 1.1 spec violated the 1.0 spec

So, a new version of the spec is created, and it changes rules. You call this violating. How can people ever release new versions of something without "violating" a prior version?

> YAML.pm was for a long time not able to read it,

I'm only asking that you stick to the truth and don't just say "YAML.pm cannot read it". It wasn't able to, and now it can.

Btw, if YAML::Syck is 1.0 and 1.0 doesn't allow it (as you think), why can YAML::Syck read it?

> The default is insecure and too slow.

The default what?

> but some clueless people prefer [...]

It's almost like you actually *want* to keep people away from working with you.

> the insecure yaml 1.2 version

That doesn't make sense. YAML 1.2 is insecure?

Reini, regarding C I'm clueless compared to you, I never really learned it, except a two week crash course.
But regarding YAML it's different.

You did not only change the XS code on top of libyaml, you also changed the libyaml code.
libyaml is still developed, although slow. I even managed to get parts of your old pull request in.
libyaml is tested against the yaml-test-suite.
Seven YAML processors (I know of) are now using the yaml-test-suite.
I'm trying to build a rich API, that does much more than just enabling or disabling loading one class.
Maybe I can port that to XS at some point. Until then, YAML::PP::LibYAML is a good alternative and at least a bit faster than pure perl.

But you are diverging and going your own way, with your own definition of what's correct and incorrect YAML, and calling everyone clueless who has got a different opinion.

My view on Open Source includes that people ideally encourage to learn from each other, at least not working against each other.
You have proven several times that you don't think this way.

**Comment by rurban** [comment]
So what is your proposed patch to the docs?

Tina Müller (tinita) <notifications@github.com> schrieb am Di., 25. Juni
2019, 12:02:

**Comment by rurban** [comment]
Docs adjusted with e536d65e897a1d880bbb1791d48057e13aea8a8c)
